### ISSUE TITLE
Compile feh with exif

### ISSUE THREAD

**Issue by Neo-Oli** [xeffyr/termux-packages#2]
https://github.com/xeffyr/termux-packages/blob/a58da6a191a1142e23ed3ad8691e3bb189edec84/packages/feh/build.sh#L9
I think this line doesn't work. `feh` still seems to be compiled without exif support. 
```
feh: unrecognized option `--draw-exif'
```

**Comment by xeffyr** [comment]
No, this line works... Just forgot to rebuild package :smile:. Now should be ok.

**Comment by Neo-Oli** [comment]
Awesome. Thanks
